"""empty message

Revision ID: 503dcbeb71d8
Revises: d2ec08a20729
Create Date: 2020-12-07 20:17:16.255678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503dcbeb71d8'
down_revision = 'd2ec08a20729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
